author: metalhedd
main: com.norcode.bukkit.buildinabox.BuildInABox
version: 0.2.0
name: BuildInABox
softdepend: [Vault, NoCheatPlus, AntiCheat]
commands:
  biab:
    usage: "/<command> [list [<page>]|[give [<player>]|save|delete|reload] <buildingname>]"
    description: give a player a Build-in-a-Box Building.

permissions:
  biab.select:
    default: op
  biab.save:
    default: op
  biab.permanent:
    default: op
  biab.delete:
    default: op
  biab.unlock.others:
    description: allow unlocking BIAB's locked by other players.
    default: true