author: metalhedd
main: com.norcode.bukkit.buildinabox.BuildInABox
version: 0.1.7-SNAPSHOT
name: BuildInABox
softdepend: [Vault, AntiCheat, NoCheatPlus]
depend: [WorldEdit]
database: true

commands:
  biab:
    usage: "/<command> [list [<page>]|[give [<player>]|save|delete] <buildingname>]"
    description: give a player a Build-in-a-Box Building.

permissions:
  biab.save:
    default: op
  biab.permanent:
    default: op
  biab.delete:
    default: op
  biab.unlock.others:
    description: allow unlocking BIAB's locked by other players.
    default: true