author: metalhedd
main: com.norcode.bukkit.buildinabox.BuildInABox
version: 0.1.5-SNAPSHOT
name: BuildInABox
softdepend: [Vault]
depend: [WorldEdit]

commands:
  biab:
    usage: "/<command> [list [<page>]|[give [<player>]|save|delete] <buildingname>]"
    description: give a player a Build-in-a-Box Building.

permissions:
  biab.admin:
    default: op
    children:
      biab.give: true
      biab.save: true
  biab.give:
    default: op
  biab.save:
    default: op
  biab.permanent:
    default: op
  biab.delete:
    default: op
  biab.place:
    description: allow placing BIABs
    default: true
  biab.pickup:
    description: allow picking up BIABs
    default: true
  biab.lock:
    description: allow locking BIAB's
    default: true
  biab.unlock:
    description: allow unlocking BIAB's locked by you
    default: true
  biab.unlock.others:
    description: allow unlocking BIAB's locked by other players.